language: ruby
before_install:
  - gem update --system
  - gem --version
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - jruby-19mode
gemfile:
  - test/gemfiles/Gemfile.rails.3.1
  - test/gemfiles/Gemfile.rails.3.2
notifications:
  recipients:
    - oleg@khabarov.ca
branches:
  only:
    - master
matrix:
  allow_failures:
    - rvm: jruby-19mode
